//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k163620_Q5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CurrencySoap")]
    public interface CurrencySoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        k163620_Q5.ServiceReference1.HelloWorldResponse HelloWorld(k163620_Q5.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        k163620_Q5.ServiceReference1.GetListResponse GetList(k163620_Q5.ServiceReference1.GetListRequest request);
        
        // CODEGEN: Generating message contract since element name convertFrom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/currencyConverter", ReplyAction="*")]
        k163620_Q5.ServiceReference1.currencyConverterResponse currencyConverter(k163620_Q5.ServiceReference1.currencyConverterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public k163620_Q5.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(k163620_Q5.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public k163620_Q5.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(k163620_Q5.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public k163620_Q5.ServiceReference1.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(k163620_Q5.ServiceReference1.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListRequestBody {
        
        public GetListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public k163620_Q5.ServiceReference1.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(k163620_Q5.ServiceReference1.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(string GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currencyConverterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="currencyConverter", Namespace="http://tempuri.org/", Order=0)]
        public k163620_Q5.ServiceReference1.currencyConverterRequestBody Body;
        
        public currencyConverterRequest() {
        }
        
        public currencyConverterRequest(k163620_Q5.ServiceReference1.currencyConverterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class currencyConverterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string convertFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string convertTo;
        
        public currencyConverterRequestBody() {
        }
        
        public currencyConverterRequestBody(double Amount, string convertFrom, string convertTo) {
            this.Amount = Amount;
            this.convertFrom = convertFrom;
            this.convertTo = convertTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currencyConverterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="currencyConverterResponse", Namespace="http://tempuri.org/", Order=0)]
        public k163620_Q5.ServiceReference1.currencyConverterResponseBody Body;
        
        public currencyConverterResponse() {
        }
        
        public currencyConverterResponse(k163620_Q5.ServiceReference1.currencyConverterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class currencyConverterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double currencyConverterResult;
        
        public currencyConverterResponseBody() {
        }
        
        public currencyConverterResponseBody(double currencyConverterResult) {
            this.currencyConverterResult = currencyConverterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CurrencySoapChannel : k163620_Q5.ServiceReference1.CurrencySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencySoapClient : System.ServiceModel.ClientBase<k163620_Q5.ServiceReference1.CurrencySoap>, k163620_Q5.ServiceReference1.CurrencySoap {
        
        public CurrencySoapClient() {
        }
        
        public CurrencySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        k163620_Q5.ServiceReference1.HelloWorldResponse k163620_Q5.ServiceReference1.CurrencySoap.HelloWorld(k163620_Q5.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            k163620_Q5.ServiceReference1.HelloWorldRequest inValue = new k163620_Q5.ServiceReference1.HelloWorldRequest();
            inValue.Body = new k163620_Q5.ServiceReference1.HelloWorldRequestBody();
            k163620_Q5.ServiceReference1.HelloWorldResponse retVal = ((k163620_Q5.ServiceReference1.CurrencySoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        k163620_Q5.ServiceReference1.GetListResponse k163620_Q5.ServiceReference1.CurrencySoap.GetList(k163620_Q5.ServiceReference1.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public string GetList() {
            k163620_Q5.ServiceReference1.GetListRequest inValue = new k163620_Q5.ServiceReference1.GetListRequest();
            inValue.Body = new k163620_Q5.ServiceReference1.GetListRequestBody();
            k163620_Q5.ServiceReference1.GetListResponse retVal = ((k163620_Q5.ServiceReference1.CurrencySoap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        k163620_Q5.ServiceReference1.currencyConverterResponse k163620_Q5.ServiceReference1.CurrencySoap.currencyConverter(k163620_Q5.ServiceReference1.currencyConverterRequest request) {
            return base.Channel.currencyConverter(request);
        }
        
        public double currencyConverter(double Amount, string convertFrom, string convertTo) {
            k163620_Q5.ServiceReference1.currencyConverterRequest inValue = new k163620_Q5.ServiceReference1.currencyConverterRequest();
            inValue.Body = new k163620_Q5.ServiceReference1.currencyConverterRequestBody();
            inValue.Body.Amount = Amount;
            inValue.Body.convertFrom = convertFrom;
            inValue.Body.convertTo = convertTo;
            k163620_Q5.ServiceReference1.currencyConverterResponse retVal = ((k163620_Q5.ServiceReference1.CurrencySoap)(this)).currencyConverter(inValue);
            return retVal.Body.currencyConverterResult;
        }
    }
}
